name: ova-backend
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./src:/code
    environment:
      - PORT=8000
      - HOST=0.0.0.0

networks:
  default:
    driver: bridge